# Generated by Django 4.1.1 on 2022-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='krosovka',
            name='turi',
            field=models.CharField(choices=[('SPORT', 'sport'), ('BAZM', 'Bazm')], default='SPORT', max_length=6),
        ),
    ]
